FROM python:3.9-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt


RUN mkdir -p /app/logs

ENV DB_HOST=postgres
ENV DB_NAME=earthquakedb
ENV DB_USER=earthquake
ENV DB_PASS=quakedata

COPY consumer.py .
COPY db_utils.py .

CMD ["python", "consumer.py"] 