FROM python:3.9-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Create logs directory
RUN mkdir -p /app/logs

# Set environment variables for database connection
ENV DB_HOST=postgres
ENV DB_NAME=earthquakedb
ENV DB_USER=earthquake
ENV DB_PASS=quakedata

COPY consumer.py .
COPY db_utils.py .

CMD ["python", "consumer.py"] 