FROM python:3.9-slim

WORKDIR /app

COPY earthquake_dashboard.py /app/
COPY requirements_dashboard.txt /app/requirements.txt

RUN pip install --no-cache-dir -r requirements.txt

EXPOSE 8501

HEALTHCHECK CMD curl --fail http://localhost:8501/_stcore/health || exit 1

ENTRYPOINT ["streamlit", "run", "earthquake_dashboard.py", "--server.port=8501", "--server.address=0.0.0.0"] 