FROM python:3.9-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt


RUN mkdir -p /app/logs

COPY producer_websocket.py .

CMD ["python", "producer_websocket.py"] 